---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: patryk-p
  labels:
    app: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
        - name: nginx-inside-1
          image: nginx:1.24.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-map
              mountPath: /etc/data
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              cpu: 200m
              memory: 200M
        - name: node20
          image: node:20-slim
          ports:
            - containerPort: 8080
          command: ["node"]
          args:
            - "-e"
            - |
              const http = require('http');
              const port = 8080;
              http.createServer((req, res) => {
                res.writeHead(200, { 'Content-Type': 'text/plain' });
                res.end('Hello from Node.js!\n');
              }).listen(port, () => {
                console.log(`Server running on http://localhost:${port}`);
              });
          volumeMounts:
            - name: config-map
              mountPath: /etc/data
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              cpu: 200m
              memory: 200M
      volumes:
        - name: config-map
          configMap:
            name: nginx-config-map
