apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: patryk-p
  labels:
    app: nginx-deploy
spec:
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      replicas: 2
      containers:
      - name: nginx-inside-1
        image: nginx:1.24.0
        volumeMounts:
        - name: configmap
          mountPath: "/etc/data"
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 100M
          limits:
            cpu: 200m
            memory: 200M
    volumes:
    - name: configmap
      configMap:
        name: nginx-config-map
